# TODO :                                               
class LoanService:
    def __init__():
        ...

    def insert_loan(self, loan):
        ...

    def select_loan(self, column, value):
        ...

    def delete_loan(self, column, value):
        ...
    def update_loan(self, column, value, updates):
        ...