import oracledb
from src.config import OracleConfig


class OracleStorage:
    def __init__(self):
        self.host = OracleConfig.DB_HOST
        self.port = OracleConfig.DB_PORT
        self.user = OracleConfig.DB_USER
        self.password = OracleConfig.DB_PASSWORD
        self.service_name = OracleConfig.DB_SERVICE

    def connect(self):
        dsn = f"{self.host}:{self.port}/{self.service_name}"
        return oracledb.connect(user=self.user, password=self.password, dsn=dsn)

    def execute(self, query, params=()):
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(query, params)
                affected = cursor.rowcount
            connection.commit()
        return affected

    def fetch_one(self, query, params=()):
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(query, params)
                return cursor.fetchone()

    def fetch_all(self, query, params=()):
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute(query, params)
                return cursor.fetchall()

    def create_tables(self):
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE '
                        CREATE TABLE books (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            book_isbn VARCHAR2(50) UNIQUE NOT NULL,
                            book_title VARCHAR2(255) NOT NULL,
                            author_name VARCHAR2(255) NOT NULL,
                            publication_year NUMBER,
                            page_count NUMBER,
                            genre VARCHAR2(100),
                            book_status VARCHAR2(50) NOT NULL,
                            physical_version VARCHAR2(10) NOT NULL,
                            digital_version VARCHAR2(10) NOT NULL,
                            count NUMBER
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN
                                RAISE;
                            END IF;
                    END;
                """)
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE '
                        CREATE TABLE members (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            member_nID VARCHAR2(20) UNIQUE NOT NULL,
                            first_name VARCHAR2(100) NOT NULL,
                            last_name VARCHAR2(100) NOT NULL,
                            phone_number VARCHAR2(20) UNIQUE,
                            status VARCHAR2(50),
                            join_date DATE
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN
                                RAISE;
                            END IF;
                    END;
                """)
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE '
                        CREATE TABLE loans (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            book_isbn VARCHAR2(50) NOT NULL,
                            member_nID VARCHAR2(20) NOT NULL,
                            loan_date DATE,

                            CONSTRAINT fk_loan_book
                                FOREIGN KEY(book_isbn)
                                REFERENCES books(book_isbn)
                                ON DELETE CASCADE,

                            CONSTRAINT fk_loan_member
                                FOREIGN KEY(member_nID)
                                REFERENCES members(member_nID)
                                ON DELETE CASCADE
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN
                                RAISE;
                            END IF;
                    END;
                """)
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE '
                        CREATE TABLE app_metadata (
                            key_name VARCHAR2(50) PRIMARY KEY,
                            value CLOB NOT NULL
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN
                                RAISE;
                            END IF;
                    END;
                """)
            connection.commit()

    def is_setup_completed(self):
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute("""
                    SELECT value
                    FROM app_metadata
                    WHERE key_name = 'setup_completed'
                """)
                row = cursor.fetchone()

                return row is not None and str(row[0]).lower() == "true"

    def mark_setup_completed(self):
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute("""
                    MERGE INTO app_metadata t
                    USING (
                        SELECT 'setup_completed' AS key_name,
                            'true' AS value
                        FROM dual
                    ) s
                    ON (t.key_name = s.key_name)
                    WHEN MATCHED THEN
                        UPDATE SET t.value = s.value
                    WHEN NOT MATCHED THEN
                        INSERT (key_name, value)
                        VALUES (s.key_name, s.value)
                """)
            connection.commit()

    def ensure_metadata_table(self):
        with self.connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE '
                        CREATE TABLE app_metadata (
                            key_name VARCHAR2(50) PRIMARY KEY,
                            value CLOB NOT NULL
                        )';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN
                                RAISE;
                            END IF;
                    END;
                """)
            connection.commit()